### ISSUE TITLE
icon does not scale with input size

### ISSUE THREAD

**Issue by danieliancu** [jgthms/bulma#159]
https://jsfiddle.net/7ovL7odh/1/

**Comment by jgthms** [comment]
You need to use a `<span class="icon">` container.

**Comment by danieliancu** [comment]
Still not working as expected https://jsfiddle.net/7ovL7odh/2/

**Comment by jgthms** [comment]
Ah yeah, I haven't pushed that fix yet.

**Comment by jgthms** [comment]
Should be fixed

**Comment by danieliancu** [comment]
Still not working with the latest version `0.0.18`.
https://jsfiddle.net/7ovL7odh/6/

**Comment by jgthms** [comment]
Ah I'm stupid. I fixed something else... Ok, I'll fix that for `0.0.19`

**Comment by danieliancu** [comment]
@jgthms No problem.

You're doing an awesome job with Bulma!
Feels like a breath of fresh air!

**Comment by jgthms** [comment]
This if fixed I believe? http://bulma.io/documentation/elements/form/
