### ISSUE TITLE
Active tab inherits wrong style when inside hero

### ISSUE THREAD

**Issue by gragland** [jgthms/bulma#3009]
### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **0.9.0**
My **browser** is: Safari 13.1
I am sure this issue is **not a duplicate**

### Description

The active tab has the wrong text color when inside a .hero element. This can be seen in the [Bulma docs hero section](https://bulma.io/documentation/layout/hero/).
![Screen Shot 2020-06-22 at 2 51 01 PM](https://user-images.githubusercontent.com/1481077/85338910-ffa0a180-b497-11ea-9099-07a31587dbcb.png)

Another example where the tab background-color and text color will be black, so the text is completely illegible:

```html
<div class="hero is-white">
  <div class="hero-body">
    <div class="tabs is-toggle ">
      <ul>
        <li class="is-active"><a href="#">General</a></li>
        <li><a href="#">Password</a></li>
     </ul>
    </div>
  </div>
</div>
```
Screenshot:
![Screen Shot 2020-06-22 at 2 34 08 PM](https://user-images.githubusercontent.com/1481077/85338272-ce73a180-b496-11ea-8dcb-d17a2beaadd9.png)

I'm only seeing this behavior on Safari. It appears to be an issue with the following CSS taking precedence:
```css
.hero.is-white a:not(.button):not(.dropdown-item):not(.tag):not(.pagination-link.is-current), .hero.is-light strong {
color: inherit;
}
```

**Comment by codecat** [comment]
Just encountered this myself on Safari 13.1.2 (15609.3.5.1.3) as well. Works fine in all other browsers.

**Comment by ReeceM** [comment]
Also on Safari 12.1.2, with version 0.7.5, 0.7.4 doesn't have the issue.

Chrome though works. This issue actually stopped me from moving up in versions, but had some time to have a look and not sure if anyone else has been getting this. But did have an idea to sort it at the user level if need be, you can do the following after the main Bulma files.

```sass
.hero
  @each $name, $pair in $colors
    $color: nth($pair, 1)
    $color-invert: nth($pair, 2)
    &.is-#{$name}
      .tabs
        &.is-boxed,
        &.is-toggle
          li.is-active a
            &,
            &:hover
              color: $color !important
```

The last line, adding `!important` seems to be enough to override the inherit section when the links are active in tabs only. That is the only implementation I have noticed, so don't know the effects it _might_ have on other elements in the hero.

Still a good package :)

**Comment by codecat** [comment]
I'm now getting this since a recent Firefox update as well. Are we sure this is really a browser bug anymore?

**Comment by hosuaby** [comment]
I confirme the same bug in Google Chrome.

**Comment by svivian** [comment]
Yep same here in Chrome and Firefox, just started happening in the past few days. Regardless of whether it's a browser bug it needs to be worked around. I'm currently adding a color explicitly to `.tabs.is-boxed .is-active` to work around it.

One way to do it in Bulma itself is replace line 28 in hero.sass:

    a:not(.button):not(.dropdown-item):not(.tag):not(.pagination-link.is-current),

with this:

    li:not(.is-active) a:not(.button):not(.dropdown-item):not(.tag):not(.pagination-link.is-current),

Haven't tested if that affects anything else though.

**Comment by xaralis** [comment]
Confirming. Same error occurs in navbar too:

![image](https://user-images.githubusercontent.com/441739/107414329-25a3b080-6b12-11eb-9cbe-84e61022bfd2.png)

Working around by using just `.dropdown-item` in place of documented `.navbar-item`.

**Comment by ruttydm** [comment]
Same issue on the chromium edge: 
![image](https://user-images.githubusercontent.com/5909558/114912589-768c9980-9e20-11eb-8745-dfecbb35c4bf.png)
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
  </head>
  <body>

    <section class="hero is-info is-small">


        <div class="hero-body">
            <div class="container">
            <p class="title">
                CardanoNFT
            </p>
            <p class="subtitle">
                Making NFT's fair to anybody.
            </p>
            </div>
        </div>

        <div class="hero-foot">
            <nav class="tabs is-boxed is-fullwidth">
            <div class="container">
                <ul>
                <li class="is-active"><a>Overview</a></li>
                <li><a>Modifiers</a></li>
                <li><a>Grid</a></li>
                <li><a>Elements</a></li>
                <li><a>Components</a></li>
                <li><a>Layout</a></li>
                </ul>
            </div>
            </nav>
        </div>

    </section>

  </body>
</html>`

**Comment by codecat** [comment]
I can not reproduce this anymore in Firefox 99.0.1 or Edge 100.0.1185.44. Was this quietly fixed by the browsers somehow?

**Comment by rakaur** [comment]
This is still absolutely the case at least in whatever version bulmaswatch's CDN puts out. Still broken in Safari and Chrome. I can't believe this one-line change has not been fixed in years. Guess I chose the wrong framework.

**Comment by gragland** [comment]
@rakaur Looks like BulmaSwatch gives you Bulma 0.8.0. I'm no longer seeing this issue with Bulma 0.9.3. Going to close this out for now since it looks to be fixed in the latest Bulma.

**Comment by Carlstain** [comment]
The issue still persists with Bulma 0.9.3 + , I've setup a [codepen](https://codepen.io/carlstain/pen/bGLzQXe) to illustrate (using bulma 0.9.4)

**Comment by grofit** [comment]
I get this exact same issue, as per shown in the codepen in previous post.

**Comment by digitigradeit** [comment]
I was able to resolve this by wrapping <nav.tabs inside <section

https://codepen.io/digitigradeit/pen/yLKxMwK
