### ISSUE TITLE
V0.3.1 - Close Button Is Not Displayed Correctly in IOS Safari

### ISSUE THREAD

**Issue by junyik** [jgthms/bulma#490]
It is about Bulma.
It is most likely a bug.

### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.3.1]
My **browser** is: IOS Safari

### Description
Close button is not displayed correctly in IOS Safari, as shown in the images attached below. Images are captured on Bulma Official Documentation Website using IOS Safari.

### Steps to Reproduce
1. Find an IOS Device with latest version of IOS and Safari
2. Browse http://bulma.io/documentation/components/modal/ OR http://bulma.io/documentation/elements/notification/

### Expected behavior
Close button is expected to be shown correctly, as per below (These images are captured using Chrome):
![1](https://cloud.githubusercontent.com/assets/23161630/22295705/da307d30-e2e5-11e6-89cc-183e8e23b247.png)
![2](https://cloud.githubusercontent.com/assets/23161630/22295717/e16db96e-e2e5-11e6-88ea-b1f197a1c40b.png)

### Actual behavior
Close button is not shown correctly in latest version of IOS Safari:
![3](https://cloud.githubusercontent.com/assets/23161630/22295746/feb5912c-e2e5-11e6-83e0-0e70905e26df.PNG)
![4](https://cloud.githubusercontent.com/assets/23161630/22295751/059dec0a-e2e6-11e6-8452-c4f35df81e05.PNG)

**Comment by xereda** [comment]
How do I solve this?

**Comment by jgthms** [comment]
This has been fixed.

**Comment by mendrik** [comment]
this hasn't been fixed. still broken on IOS and 0.4.2

**Comment by feeekkk** [comment]
I am still having this issue on:

Chrome on iOS and 0.4.2
Safari on iOS and 0.4.2

Please consider reopening.

**Comment by johan13** [comment]
This is a screenshot from the message component documentation on bulma.io as it looks on iPad Safari: ![img_0002](https://user-images.githubusercontent.com/643284/27991720-ffd87a80-647f-11e7-9031-8c42c3e2f500.PNG)

I think this bug should be reopened.

**Comment by johan13** [comment]
@jgthms, you closed this issue. Do you think we should re-open it? Or should I submit a separate bug?

**Comment by htfy96** [comment]
Stil broken on iOS9:

![screenshot from 2017-07-27 13-07-37](https://user-images.githubusercontent.com/8121231/28655245-fb340e80-72cc-11e7-919a-2c46829b2162.png)
