### ISSUE TITLE
Use of .container as first child of .navbar

### ISSUE THREAD

**Issue by Come2Daddy** [jgthms/bulma#896]
### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs** 
 I'm using Bulma **version** [0.4.3]

### Description

Migrating from **deprecated** nav component to navbar. (Hero layout docs are deprecated btw). Used to place .container inside of nav component to align nav elements with page elements. Now .container placed inside navbar component breaks navbar-brand and navbar-menu on two rows.

### Steps to Reproduce

Use .container as first child of .navbar

### Expected behavior

Limit navbar elements to .container size in one row

### Actual behavior

Breaks navbar elements into rows (navbar-brand & navbar-menu)

**Comment by drisschelouati** [comment]
I made a project with version 0.3.2 and the nav component deprecation is giving me a hard Time as it breaks my navigation, probably related to this issue. And my custom hover dropdown is not working anymore.

**Comment by jgthms** [comment]
This is fixed in `0.4.4`.

**Comment by kissmygritts** [comment]
This still happens in `0.5.0`. https://codepen.io/kissmygritts/pen/jLMbJQ?editors=1100

**Comment by drisschelouati** [comment]
Yes. Besides, i really liked the old nav component and is one of the main reasons i switched to bulma for my projects. Isnt there a way to keep both (with Hero head and all stuff)? This is a serious question.

**Comment by antonkeller** [comment]
Simply add this to your container: `display: flex;`

**Comment by antonkeller** [comment]
Also see:  https://github.com/jgthms/bulma/issues/841#issuecomment-314112318
